name: iv_project_invitation_theme
description: "IV Project Invitation Theme"
version: 0.2.2
homepage:
publish_to: "none"

environment:
  sdk: ^3.10.8
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  iv_project_model:
    path: ../iv_project_model

  iv_project_web_data:
    path: ../iv_project_web_data

  iv_project_core:
    path: ../iv_project_core

  iv_project_widget_core:
    path: ../iv_project_widget_core

  quick_dev_sdk:
    path: ../quick_dev_sdk

  bloc: ^9.2.0
  flutter_bloc: ^9.1.1

  equatable: ^2.0.7

  intl: ^0.20.2

  just_audio: ^0.10.5

  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  http: ^1.6.0

  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/
    - assets/dummys/
    - assets/avatars/
    - assets/banks/
    - assets/icons/
    - assets/logos/
