name: iv_project_invitation_theme
description: "IV Project Invitation Theme"
version: 0.1.8+2
homepage:
publish_to: 'none'

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # iv_project_model:
  #   path: ../iv_project_model
  
  iv_project_model:
    git:
      url: https://github.com/faequl96/iv_project_model.git
      ref: 0.0.9

  # iv_project_core:
  #   path: ../iv_project_core

  iv_project_core:
    git:
      url: https://github.com/faequl96/iv_project_core.git
      ref: 0.0.7
  
  # quick_dev_sdk:
  #   path: ../quick_dev_sdk

  quick_dev_sdk:
    git:
      url: https://github.com/faequl96/quick_dev_sdk.git
      ref: 0.0.8

  flutter_bloc: ^9.1.1

  equatable: ^2.0.7

  intl: ^0.20.2

  just_audio: ^0.10.5

  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/
    - assets/dummys/
    - assets/avatars/
    - assets/banks/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

        - asset: assets/fonts/Inter-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic
    
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    
    - family: ArefRuqaa
      fonts:
        - asset: assets/fonts/ArefRuqaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/ArefRuqaa-Bold.ttf
          weight: 700
